#!/usr/bin/env bun
// ---------------------------------------------------------------------------
// action-entry.ts — GitHub Action entry point for ultrareview v2
// Reads PR context from GitHub Actions env vars, runs the agent pipeline,
// and posts line-level review comments back to the PR.
// ---------------------------------------------------------------------------

async function main() {
  // PR_NUMBER from action input, PR_NUMBER_OVERRIDE from issue_comment trigger
  const prNumber = process.env.PR_NUMBER || process.env.PR_NUMBER_OVERRIDE
  const owner = process.env.REPO_OWNER ?? process.env.GITHUB_REPOSITORY_OWNER
  const repoName = process.env.REPO_NAME ?? process.env.GITHUB_REPOSITORY?.split('/')[1]
  const repoRoot = process.cwd()

  if (!prNumber || !owner || !repoName) {
    console.error(
      'Missing required env vars: PR_NUMBER, REPO_OWNER (or GITHUB_REPOSITORY_OWNER), REPO_NAME (or GITHUB_REPOSITORY)',
    )
    process.exit(1)
  }

  // Check if PR was closed/merged → label feedback instead of reviewing
  const eventAction = process.env.GITHUB_EVENT_ACTION ?? ''
  if (eventAction === 'closed') {
    console.log(`[feedback] PR #${prNumber} closed — labeling feedback`)
    const { labelFeedback } = await import('../eval/feedback-collector.ts')
    await labelFeedback({ owner, repo: repoName, prNumber: parseInt(prNumber, 10) }).catch(
      (err: unknown) => console.warn(`[feedback] Label failed: ${err instanceof Error ? err.message : err}`),
    )
    process.exit(0)
  }

  const minConfidence = process.env.FILTER_MIN_CONFIDENCE ?? '0.7'
  const minJudgeScore = process.env.FILTER_MIN_JUDGE_SCORE ?? '0.6'
  console.log(`Ultrareview v2 — PR #${prNumber} on ${owner}/${repoName}`)
  console.log(`Filter thresholds — confidence: ${minConfidence}, judge: ${minJudgeScore}`)

  // ---------------------------------------------------------------------------
  // Step 1: Fetch PR diff via gh CLI
  // ---------------------------------------------------------------------------

  let diffText: string
  try {
    diffText = await Bun.$`gh pr diff ${prNumber} --repo ${owner}/${repoName}`.quiet().text()
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error(`Failed to fetch diff: ${msg}`)
    // Don't fail the Action — gh might not have access, just log and exit
    process.exit(0)
  }

  if (!diffText.trim()) {
    console.log('Empty diff — nothing to review.')
    process.exit(0)
  }

  console.log(`Diff: ${diffText.length} chars`)

  // ---------------------------------------------------------------------------
  // Step 2: Run the 7-step agent loop
  // ---------------------------------------------------------------------------

  const { runAgentLoop } = await import('../agent/agent-loop.ts')

  const result = await runAgentLoop(diffText, repoRoot, (step: string, detail: string) => {
    console.log(`[${step}] ${detail}`)
  })

  console.log(`Found ${result.bugs.length} bug(s) in ${result.duration}ms`)

  // ---------------------------------------------------------------------------
  // Step 3: Post review comments or LGTM
  // ---------------------------------------------------------------------------

  if (result.bugs.length > 0) {
    const { postPrReview } = await import('./pr-comments.ts')

    const { commentCount } = await postPrReview({
      owner,
      repo: repoName,
      prNumber: parseInt(prNumber, 10),
      bugs: result.bugs,
      diffText,
      duration: result.duration,
    })

    console.log(`Posted ${commentCount} review comment(s) on PR #${prNumber}`)

    // Save to feedback dataset for self-improving loop
    const { saveFeedback } = await import('../eval/feedback-collector.ts')
    await saveFeedback({ owner, repo: repoName, prNumber: parseInt(prNumber, 10), diffText, result }).catch(
      (err: unknown) => console.warn(`[feedback] Save failed: ${err instanceof Error ? err.message : err}`),
    )
  } else {
    // Post a simple LGTM comment when no bugs detected
    await Bun.$`gh pr comment ${prNumber} --repo ${owner}/${repoName} --body ${'## ✅ Ultrareview: No issues found\n\nLGTM! No bugs detected by the automated review pipeline.\n\n*Generated by ultrareview-clone v2*'}`.quiet()
    console.log('No issues found — posted LGTM comment')
  }
}

main().catch((err) => {
  const msg = err instanceof Error ? err.message : String(err)
  console.error('Ultrareview failed:', msg)
  // Exit 0 to avoid blocking the PR with a failing status check
  process.exit(0)
})
