// ---------------------------------------------------------------------------
// pr-comments.ts — Post bug-hunter results as line-level GitHub PR review
// Uses gh CLI for auth; payload written to temp file to avoid stdin issues.
// ---------------------------------------------------------------------------

import type { Bug } from '../utils/mock-fleet.ts'
import { parseDiff, lineToDiffPosition, type DiffFile } from './diff-parser.ts'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { writeFileSync, unlinkSync } from 'node:fs'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type ReviewComment = {
  path: string
  line: number     // line in the new file
  position?: number // diff position (for GH API, optional debug)
  body: string     // markdown formatted
}

// ---------------------------------------------------------------------------
// Severity helpers
// ---------------------------------------------------------------------------

const SEVERITY_EMOJI: Record<Bug['severity'], string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '⚪',
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1)
}

// ---------------------------------------------------------------------------
// bugsToReviewComments — map Bug[] to ReviewComment[] using diff positions
// Bugs whose lines are not in the diff are skipped (not a failure).
// ---------------------------------------------------------------------------

export function bugsToReviewComments(bugs: Bug[], diffFiles: DiffFile[]): ReviewComment[] {
  const comments: ReviewComment[] = []

  for (const bug of bugs) {
    if (!bug.line) continue // no line info — cannot post as line comment

    // Match diff file by path suffix (bugs may use relative paths)
    const diffFile = diffFiles.find(
      (f) => f.path === bug.file || f.path.endsWith(bug.file) || bug.file.endsWith(f.path),
    )
    if (!diffFile) continue

    const position = lineToDiffPosition(diffFile, bug.line)
    if (position === null) continue // line not in diff — skip gracefully

    const emoji = SEVERITY_EMOJI[bug.severity]
    const lang = diffFile.path.split('.').pop() ?? ''

    const body = [
      `**${emoji} ${capitalize(bug.severity)}: ${bug.title}**`,
      '',
      '```' + lang,
      `// Line ${bug.line}`,
      '```',
      '',
      bug.description,
      '',
      `**Suggestion:** ${bug.suggestion}`,
      '',
      `*Confidence: ${bug.verified ? 'verified' : 'unverified'} · Severity: ${bug.severity}*`,
    ].join('\n')

    comments.push({ path: diffFile.path, line: bug.line, position, body })
  }

  return comments
}

// ---------------------------------------------------------------------------
// buildReviewSummary — markdown table with stats for the review body
// ---------------------------------------------------------------------------

export function buildReviewSummary(bugs: Bug[], duration: number): string {
  const verified = bugs.filter((b) => b.verified).length
  const refuted = bugs.filter((b) => !b.verified).length
  const durationSec = (duration / 1000).toFixed(1)

  const bySeverity = {
    critical: bugs.filter((b) => b.severity === 'critical').length,
    high: bugs.filter((b) => b.severity === 'high').length,
    medium: bugs.filter((b) => b.severity === 'medium').length,
    low: bugs.filter((b) => b.severity === 'low').length,
  }

  const severityLines = [
    bySeverity.critical > 0 ? `- 🔴 Critical: ${bySeverity.critical}` : null,
    bySeverity.high > 0 ? `- 🟠 High: ${bySeverity.high}` : null,
    bySeverity.medium > 0 ? `- 🟡 Medium: ${bySeverity.medium}` : null,
    bySeverity.low > 0 ? `- ⚪ Low: ${bySeverity.low}` : null,
  ]
    .filter((s): s is string => s !== null)
    .join('\n')

  return [
    '## 🔍 Ultrareview Results',
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Bugs found | ${bugs.length} |`,
    `| Verified | ${verified} |`,
    `| Refuted | ${refuted} |`,
    `| Duration | ${durationSec}s |`,
    '',
    '### By Severity',
    severityLines || '- No bugs found',
    '',
    '*Generated by ultrareview-clone v2*',
  ].join('\n')
}

// ---------------------------------------------------------------------------
// postPrReview — write payload to temp file and post via gh api
// ---------------------------------------------------------------------------

export async function postPrReview(options: {
  owner: string
  repo: string
  prNumber: number
  bugs: Bug[]
  diffText: string
  duration: number
}): Promise<{ commentCount: number }> {
  const { owner, repo, prNumber, bugs, diffText, duration } = options

  // If no bugs, post a simple LGTM comment instead of a review
  if (bugs.length === 0) {
    const lgtmBody = '## ✅ Ultrareview: LGTM\n\nNo bugs found in this diff. Looks good to me!\n\n*Generated by ultrareview-clone v2*'
    const lgtmTmp = join(tmpdir(), `ultrareview-lgtm-${Date.now()}.json`)
    try {
      writeFileSync(lgtmTmp, JSON.stringify({ body: lgtmBody }))
      await Bun.$`gh api repos/${owner}/${repo}/issues/${prNumber}/comments --method POST --input ${lgtmTmp}`.quiet()
    } finally {
      try { unlinkSync(lgtmTmp) } catch { /* ignore */ }
    }
    return { commentCount: 0 }
  }

  const diffFiles = parseDiff(diffText)
  const comments = bugsToReviewComments(bugs, diffFiles)
  const summary = buildReviewSummary(bugs, duration)

  const payload = {
    body: summary,
    event: 'COMMENT',
    comments: comments.map((c) => ({ path: c.path, line: c.line, body: c.body })),
  }

  // Write payload to temp file to avoid stdin/shell quoting issues
  const tmpFile = join(tmpdir(), `ultrareview-review-${Date.now()}.json`)
  try {
    writeFileSync(tmpFile, JSON.stringify(payload))
    await Bun.$`gh api repos/${owner}/${repo}/pulls/${prNumber}/reviews --method POST --input ${tmpFile}`.quiet()
  } finally {
    try { unlinkSync(tmpFile) } catch { /* ignore cleanup errors */ }
  }

  return { commentCount: comments.length }
}
