#!/usr/bin/env bash
# prepare-release.sh — Idempotent helper for the manual Version PR flow.
#
# cyberk-dev org blocks Actions from creating PRs, so we open the Version PR
# locally; the workflow on merge handles tagging + GH release creation.
#
# Steps:
#   1. Verify clean working tree on main (with origin/main pull)
#   2. bun run changeset:version  (consolidate .changeset/* → CHANGELOG, bump pkg)
#   3. Create branch release/v<new-version>
#   4. Commit chore(release): v<new>
#   5. Push branch -u origin
#   6. Open PR via gh
#   7. Print merge instructions
#
# Usage:
#   bash scripts/prepare-release.sh             # do it
#   bash scripts/prepare-release.sh --dry-run   # preview only

set -euo pipefail

DRY_RUN=0
for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    -h|--help)
      sed -n '2,20p' "$0"
      exit 0
      ;;
  esac
done

run() {
  echo "+ $*"
  if [ "$DRY_RUN" -eq 0 ]; then
    "$@"
  fi
}

# ---------------------------------------------------------------------------
# Guards
# ---------------------------------------------------------------------------

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
if [ "$CURRENT_BRANCH" != "main" ]; then
  echo "ERROR: must be on 'main' (currently on '$CURRENT_BRANCH')." >&2
  exit 1
fi

if [ -n "$(git status --porcelain)" ]; then
  echo "ERROR: working tree not clean. Commit or stash first." >&2
  git status --short
  exit 1
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "ERROR: 'gh' CLI not found. Install + auth first." >&2
  exit 1
fi

# Pull latest main
run git fetch origin main
run git pull --ff-only origin main

# Need at least one changeset
shopt -s nullglob
CHANGESETS=(.changeset/*.md)
NON_README_COUNT=0
for f in "${CHANGESETS[@]}"; do
  base=$(basename "$f")
  if [ "$base" != "README.md" ]; then
    NON_README_COUNT=$((NON_README_COUNT + 1))
  fi
done
if [ "$NON_README_COUNT" -eq 0 ]; then
  echo "ERROR: no pending changesets in .changeset/. Nothing to release." >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Bump
# ---------------------------------------------------------------------------

CURRENT_VERSION=$(node -p "require('./package.json').version")
echo "Current version: $CURRENT_VERSION"

run bun run changeset:version

NEW_VERSION=$(node -p "require('./package.json').version")
echo "New version: $NEW_VERSION"

if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
  echo "ERROR: changeset:version did not bump the version. Aborting." >&2
  # Roll back any partial state
  run git checkout -- .
  exit 1
fi

BRANCH="release/v${NEW_VERSION}"

# Branch + commit + push
run git checkout -b "$BRANCH"
run git add -A
run git commit -m "chore(release): v${NEW_VERSION}"
run git push -u origin "$BRANCH"

# Open PR
PR_BODY="Automated version PR for v${NEW_VERSION}.

Generated by \`scripts/prepare-release.sh\`. Consolidates pending changesets into the CHANGELOG and bumps \`package.json\`.

On merge, \`.github/workflows/release.yml\` will tag \`v${NEW_VERSION}\` and create the GitHub Release."

if [ "$DRY_RUN" -eq 0 ]; then
  gh pr create --title "chore(release): v${NEW_VERSION}" --body "$PR_BODY"
else
  echo "+ gh pr create --title 'chore(release): v${NEW_VERSION}' --body '<...>'"
fi

cat <<EOF

✅ Release branch ready: ${BRANCH}

Next steps:
  1. Review the auto-generated diff (CHANGELOG.md + package.json)
  2. Merge the PR
  3. The release workflow will tag v${NEW_VERSION} and create the GH release
  4. Verify: gh release view v${NEW_VERSION}

EOF
